### ISSUE TITLE
Update plugin for 2021.2

### ISSUE THREAD

**Issue by andersodt** [ChrisCarini/jetbrains-auto-power-saver#12]
The current version of RubyMine disables this plugin because it is not compatible.

**Comment by ChrisCarini** [comment]
Hi @andersodt - Thank you for opening this issue. I have just published version `2.5.0` to the JeBrains Plugin Marketplace - please allow for a few days for JetBrains to approve the plugin, and you should receive a notification to upgrade.

**Comment by andersodt** [comment]
Thank you for the prompt response. This is a great plugin, thank you for your hard work!

**Comment by ChrisCarini** [comment]
Absolutely! Glad you like the plugin @andersodt ! :) Appreciate the kind words!

**Comment by ChrisCarini** [comment]
@all-contributors please add @andersodt for bug
