### ISSUE TITLE
Update plugin for 2023.1

### ISSUE THREAD

**Issue by ristomatti** [ChrisCarini/jetbrains-auto-power-saver#123]
Screenshot says it all:

![image](https://user-images.githubusercontent.com/9029939/228354355-b9046c85-62f1-47f8-855f-d202c6cf53b6.png)

Thank you for this awesome plugin, it keeps my annoying CPU fan at bay!

**Comment by ChrisCarini** [comment]
Hi @ristomatti - a version compatible with 2023.1 has been released: https://plugins.jetbrains.com/plugin/11941-automatic-power-saver/versions

Thank you for using the plugin, I hope you are enjoying it! 🎉

**Comment by ChrisCarini** [comment]
@all-contributors please add @ristomatti for maintenance
