### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by Xplouder** [ChrisCarini/jetbrains-auto-power-saver#2]
Better explain this with an example:
- Start Program 1 (example: PHPStorm)
- Start Program 2 (same "type" as Program 1, in this case, PHPStorm too)
- Let the power mode plugin trigger
- Both windows of the previously started programs went to idle
- Open window of Program 1
- The power mode plugin will remove the idle from Program 1 (as expected) but from program 2 too (not expected).

Expected: program 1 and program 2 being independent.

Note: I tested with Pycharm and PHPStorm and they seem to not share the same plugin context, resulting in the correct behavior. So I believe the problem is when you have multiple instances of the same program.

Thank You.

**Comment by ChrisCarini** [comment]
Hey @Xplouder - Thanks for opening this issue! Just to clarify, are you running two independent instances of the respective IDE, or do you just have a single application instance with multiple projects open?

I can reproduce this if you are talking about a single application with multiple projects open in separate windows, and this is expected given the architecture of JetBrains IDEs (their power saver works across the entire application, not across specific projects).

Please let me know which of these two scenarios you are describing here.

**Comment by Xplouder** [comment]
You are right. When I said about the new instances I meant new windows (i thought that they would just spawn a new program/master process, which apparently is not what happens after a quick test). Is there any chance to manage the trigger of this plugin per window(project)?

**Comment by allanlaal** [comment]
can confirm on:
`IntelliJ IDEA 2020.3.3 (Ultimate Edition)
Build #IU-203.7717.56, built on March 15, 2021`

## steps:

* open any IntelliJ IDE
* then open lots of projects from that same IDE window
* select 1 random project and File→☑Power Save Mode 

## Expected:

That 1 project has Power Save Mode enabled, others don't

## Actual:

Power Save Mode toggle is global


## Dirty fix:

#WIP I guess cloning my profile for each project and syncing (all?) settings with the IntellIJ Settings Repository plugin

**Comment by ChrisCarini** [comment]
Hi @Xplouder and @allanlaal - I am going to close out this issue. The architecture of the JetBrains [`PowerSaveMode`](https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/ide/PowerSaveMode.java) class (what this plugin uses to enable / disable power save mode is such that it only works for the entire application - that is, if you have a single IDE open with many project open in their own window, power save mode is applicable for *all* projects opened in that application. As such, I am going to close this issue - if JetBrains ever changes this, please reopen this issue and I am happy to accommodate this request!

**Comment by ChrisCarini** [comment]
@all-contributors

please add @Xplouder for bug, idea
please add @allanlaal for bug, idea

**Comment by ChrisCarini** [comment]
@all-contributors

please add @Xplouder for bug, idea
please add @allanlaal for bug, idea

**Comment by ChrisCarini** [comment]
@all-contributors

please add @Xplouder for bug, idea
please add @allanlaal for bug, idea

**Comment by ChrisCarini** [comment]
@all-contributors

please add @Xplouder for bug, idea
please add @allanlaal for bug, idea
