### ISSUE TITLE
Let's get ready for IntelliJ 2024.2

### ISSUE THREAD

**Issue by CXwudi** [ChrisCarini/jetbrains-auto-power-saver#397]
![image](https://github.com/user-attachments/assets/2c603903-9a25-4cdd-ada7-0936c8db7713)

**Comment by CXwudi** [comment]
Oh nvm, I saw the PR https://github.com/ChrisCarini/jetbrains-auto-power-saver/pull/396. Close me when the PR is merged :)

**Comment by Elvis-Zhou** [comment]
ready?

**Comment by CXwudi** [comment]
`v4.0.5` is still not updated to Intellij `2024.2` platform
