### ISSUE TITLE
Update to work with 221.*

### ISSUE THREAD

**Issue by sballance** [ChrisCarini/jetbrains-auto-power-saver#45]
![image](https://user-images.githubusercontent.com/16885530/163229233-05942a96-a7f0-477e-b9db-429c3b357af2.png)

```
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
```

**Comment by ChrisCarini** [comment]
@sballance - Thank you for opening this issue! The updated plugin has been released to the JetBrains plugin marketplace. You should be able to upgrade within your IDE - thank you for using this plugin, I hope you are enjoying it!

**Comment by ChrisCarini** [comment]
@all-contributors please add @sballance for maintenance
