### ISSUE TITLE
Not works with latest RubyMine 2022.3 (and other JetBrains IDE)

### ISSUE THREAD

**Issue by ukolovda** [ChrisCarini/jetbrains-auto-power-saver#76]
It is fine plugin, but now it say:
"Not compatible with the version of your running IDE (RubyMine 2022.3)"

Please fix, if possible.

**Comment by lkraav** [comment]
It's under construction in #75

**Comment by ChrisCarini** [comment]
@all-contributors please add @ukolovda for bug, maintenance

**Comment by ChrisCarini** [comment]
@all-contributors please add @lkraav for question
